# Collision stats

__June 2026__

Answering 2 key questions:
- What fraction of casualties are female?
- What fraction of casualties at a junction are female?

In [160]:
import yaml
import pandas as pd
import numpy as np

from yaml import Loader
from scipy.stats import binomtest
from statsmodels.stats.proportion import proportion_confint

## Read in collision & casualty data

In [161]:
params = yaml.load(open("../params.yaml", 'r'), Loader=Loader)
collisions = pd.read_csv('../data/pedestrian-and-cyclist-collisions.csv')

casualties = pd.read_csv('../data/casualties.csv')
casualties['year'] = casualties['collision_id'].apply(lambda x: int(str(x)[0:4]))

casualties

print('Junction types:')
print(params['valid_junction_types'])

collisions.head(3)

Junction types:
['roundabout', 'mini_roundabout', 't_or_staggered_junction', 'slip_road', 'crossroads', 'multi_junction', 'other_junction', 'unknown']

,raw_collision_id,borough,easting,northing,location,collision_severity,junction_detail,road_type,date,time,...,max_pedestrian_severity,male_cyclist_casualties,female_cyclist_casualties,unknown_gender_cyclist_casualties,male_pedestrian_casualties,female_pedestrian_casualties,unknown_gender_pedestrian_casualties,recency_weight,is_cyclist_collision,is_pedestrian_collision
0,1240486807,CAMDEN,527188.0,184782.0,"ON BELSIZE PARK GARDENS, NEAR THE JUNCTION WIT...",slight,t_or_staggered_junction,Single Cwy,2024-01-01,01:00:00,...,NaN,0,0,1,0,0,0,1.0,True,False
1,1240486828,LEWISHAM,536554.0,178468.0,"ON GROVE STREET, NEAR THE JUNCTION WITH OXESTA...",slight,no_junction_in_20m,roundabout,2024-01-01,00:35:00,...,slight,0,0,0,0,1,0,1.0,False,True
2,1240486841,WESTMINSTER,529084.0,181324.0,"LOCATION UNCERTAIN GREAT PORTLAND STREET, NEAR...",slight,crossroads,Dual Cwy,2024-01-01,02:15:00,...,slight,0,0,0,0,2,0,1.0,False,True

In [162]:
junction_collision_ids = collisions['raw_collision_id'].tolist()
junction_collision_ids[0:5]

[1240486807, 1240486828, 1240486841, 1240486874, 1240486897]

In [163]:
# filtering mask
casualty_mask = casualties['mode_of_travel'] == 'pedal_cycle'
severity_mask = (
    (casualties['casualty_severity'] == 'serious') |
    (casualties['casualty_severity'] == 'fatal')
)
junction_mask = casualties['raw_collision_id'].isin(junction_collision_ids)

In [164]:
all = (
    casualties[casualty_mask]
    .groupby(['casualty_gender', 'casualty_severity'])['raw_collision_id']
    .count()
    .reset_index()
    .pivot(
        index='casualty_gender',
        columns='casualty_severity',
        values='raw_collision_id'
    )
    .fillna(0)
    .reset_index()
    # .T
)
all['type'] = 'all'

at_junction = (
    casualties[casualty_mask & junction_mask]
    .groupby(['casualty_gender', 'casualty_severity'])['raw_collision_id']
    .count()
    .reset_index()
    .pivot(
        index='casualty_gender',
        columns='casualty_severity',
        values='raw_collision_id'
    )
    .fillna(0)
    .reset_index()
    # .T
)
at_junction['type'] = 'at_junction'

casualty_counts = pd.concat([
    all,
    at_junction
])

severities = ['fatal', 'serious', 'slight']
for s in severities:
    casualty_counts[f'%_{s}'] = 100 * (
        casualty_counts[s] / casualty_counts[severities].sum(axis=1)
    )

casualty_counts

casualty_severity,casualty_gender,fatal,serious,slight,type,%_fatal,%_serious,%_slight
0,Female,12.0,1110.0,4435.0,all,0.215944,19.974807,79.809250
1,Male,28.0,3666.0,15027.0,all,0.149565,19.582287,80.268148
2,Unknown,0.0,13.0,546.0,all,0.000000,2.325581,97.674419
0,Female,10.0,878.0,3742.0,at_junction,0.215983,18.963283,80.820734
1,Male,21.0,2828.0,12357.0,at_junction,0.138103,18.597922,81.263975
2,Unknown,0.0,11.0,447.0,at_junction,0.000000,2.401747,97.598253

In [165]:
all = (
    casualties[casualty_mask]
    .groupby(['casualty_gender', 'casualty_severity'])['raw_collision_id']
    .count()
    .reset_index()
    .pivot(
        index='casualty_severity',
        columns='casualty_gender',
        values='raw_collision_id'
    )
    .fillna(0)
    .reset_index()
)
all['type'] = 'all'

at_junction = (
    casualties[casualty_mask & junction_mask]
    .groupby(['casualty_gender', 'casualty_severity'])['raw_collision_id']
    .count()
    .reset_index()
    .pivot(
        index='casualty_severity',
        columns='casualty_gender',
        values='raw_collision_id'
    )
    .fillna(0)
    .reset_index()
)
at_junction['type'] = 'at_junction'

casualty_counts = pd.concat([
    all,
    at_junction
]).set_index('type').reset_index()

genders = ['Female', 'Male', 'Unknown']
for g in genders:
    casualty_counts[f'%_{g}'] = np.round(100 * (
        casualty_counts[g] / casualty_counts[genders].sum(axis=1)
    ), 2)

casualty_counts

casualty_gender,type,casualty_severity,Female,Male,Unknown,%_Female,%_Male,%_Unknown
0,all,fatal,12.0,28.0,0.0,30.00,70.00,0.00
1,all,serious,1110.0,3666.0,13.0,23.18,76.55,0.27
2,all,slight,4435.0,15027.0,546.0,22.17,75.10,2.73
3,at_junction,fatal,10.0,21.0,0.0,32.26,67.74,0.00
4,at_junction,serious,878.0,2828.0,11.0,23.62,76.08,0.30
5,at_junction,slight,3742.0,12357.0,447.0,22.62,74.68,2.70

In [166]:
casualty_counts[
    (casualty_counts['type'] == 'at_junction')
    & (casualty_counts['casualty_severity'] != 'fatal')
][genders].sum().sum()

np.float64(20263.0)

In [167]:
# at junction only
type_mask = casualty_counts['type'] == 'at_junction'

female_non_fatal = int(casualty_counts[
    type_mask
    & (casualty_counts['casualty_severity'] != 'fatal')
]['Female'].sum())

non_fatal = int(casualty_counts[
    type_mask
    & (casualty_counts['casualty_severity'] != 'fatal')
][genders].sum().sum())

female_fatals = int(casualty_counts[
    type_mask
    & (casualty_counts['casualty_severity'] == 'fatal')
]['Female'].sum())

fatals = int(casualty_counts[
    type_mask
    & (casualty_counts['casualty_severity'] == 'fatal')
][genders].sum().sum())

print(female_non_fatal, non_fatal, female_fatals, fatals)

baseline_female_rate = female_non_fatal / non_fatal  # ~0.23
print(baseline_female_rate)

result = binomtest(k=10, n=fatals, p=baseline_female_rate, alternative='greater')
low, high = proportion_confint(count=10, nobs=fatals, method='wilson')

print(f"p-value: {result.pvalue:.3f}")
print(f"95% CI: {low:.1%} – {high:.1%}")

4620 20263 10 31
0.22800177663722054
p-value: 0.149
95% CI: 18.6% – 49.9%